/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package data;

/**
 *
 * @author mdama
 */
public class ScientificCalc extends javax.swing.JFrame {

    /**
     * Creates new form ScientificCalc
     */
    public ScientificCalc() {
        initComponents();
        jRadioButton2.setEnabled(false);
    }
    
    double num1,num2,result;
    String opr;
    public void enable(){
        jTextField1.setEnabled(true);
        
        
        jRadioButton2.setEnabled(false);
        jRadioButton2.setEnabled(true);
        
        rSButtonHover24.setEnabled(true);
        rSButtonHover25.setEnabled(true);
        rSButtonHover26.setEnabled(true);
        rSButtonHover27.setEnabled(true);
        rSButtonHover28.setEnabled(true);
        rSButtonHover29.setEnabled(true);
        rSButtonHover30.setEnabled(true);
        rSButtonHover31.setEnabled(true);
        rSButtonHover9.setEnabled(true);
        rSButtonHover35.setEnabled(true);
    }
    
    public void disable(){
        jTextField1.setEnabled(false);
        
        
        jRadioButton2.setEnabled(true);
        jRadioButton2.setEnabled(false);
        
        rSButtonHover24.setEnabled(false);
        rSButtonHover25.setEnabled(false);
        rSButtonHover26.setEnabled(false);
        rSButtonHover27.setEnabled(false);
        rSButtonHover28.setEnabled(false);
        rSButtonHover29.setEnabled(false);
        rSButtonHover30.setEnabled(false);
        rSButtonHover31.setEnabled(false);
        rSButtonHover9.setEnabled(false);
        rSButtonHover35.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover7 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover2 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover3 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover4 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover5 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover6 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover8 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover9 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover10 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover11 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover12 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover13 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover14 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover15 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover16 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover17 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover18 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover19 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover20 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover22 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover23 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover24 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover25 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover26 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover27 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover28 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover29 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover30 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover31 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover32 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover33 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover34 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover35 = new rojeru_san.complementos.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scientific Calculator");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 350, 80));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        rSButtonHover1.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover1.setText("+/-");
        rSButtonHover1.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover1.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover1.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover1.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        rSButtonHover7.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover7.setText("n!");
        rSButtonHover7.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover7.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover7.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover7.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover7ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        rSButtonHover2.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover2.setText("tan");
        rSButtonHover2.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover2.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover2.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover2.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        rSButtonHover3.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover3.setText("1/x");
        rSButtonHover3.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover3.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover3.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover3.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        rSButtonHover4.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover4.setText("x^y");
        rSButtonHover4.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover4.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover4.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover4.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        rSButtonHover5.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover5.setText("x^3");
        rSButtonHover5.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover5.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover5.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover5.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        rSButtonHover6.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover6.setText("x^2");
        rSButtonHover6.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover6.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover6.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover6.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        rSButtonHover8.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/sqrt.png"))); // NOI18N
        rSButtonHover8.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover8.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover8.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover8.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover8ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        rSButtonHover9.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover9.setText("8");
        rSButtonHover9.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover9.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover9.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover9.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover9ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        rSButtonHover10.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover10.setText("sin");
        rSButtonHover10.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover10.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover10.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover10.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover10ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        rSButtonHover11.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover11.setText("cos");
        rSButtonHover11.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover11.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover11.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover11.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover11ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        rSButtonHover12.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover12.setText("exp");
        rSButtonHover12.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover12.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover12.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover12.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover12ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        rSButtonHover13.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover13.setText("log");
        rSButtonHover13.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover13.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover13.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover13.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover13ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        rSButtonHover14.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover14.setText("sinh");
        rSButtonHover14.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover14.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover14.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover14.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover14ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        rSButtonHover15.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover15.setText("cosh");
        rSButtonHover15.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover15.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover15.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover15.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover15ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        rSButtonHover16.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover16.setText("tanh");
        rSButtonHover16.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover16.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover16.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover16.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover16ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        rSButtonHover17.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover17.setText("+");
        rSButtonHover17.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover17.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover17.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover17.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover17ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        rSButtonHover18.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover18.setText("-");
        rSButtonHover18.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover18.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover18.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover18.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover18ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        rSButtonHover19.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover19.setText("*");
        rSButtonHover19.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover19.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover19.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover19.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover19ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        rSButtonHover20.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover20.setText("/");
        rSButtonHover20.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover20.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover20.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover20.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover20ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        rSButtonHover22.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover22.setText("=");
        rSButtonHover22.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover22.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover22.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover22.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover22ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 130, -1));

        rSButtonHover23.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover23.setText(".");
        rSButtonHover23.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover23.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover23.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover23.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover23ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        rSButtonHover24.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover24.setText("0");
        rSButtonHover24.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover24.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover24.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover24.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover24ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        rSButtonHover25.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover25.setText("1");
        rSButtonHover25.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover25.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover25.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover25.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover25ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        rSButtonHover26.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover26.setText("2");
        rSButtonHover26.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover26.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover26.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover26.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover26ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        rSButtonHover27.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover27.setText("3");
        rSButtonHover27.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover27.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover27.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover27.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover27ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        rSButtonHover28.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover28.setText("6");
        rSButtonHover28.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover28.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover28.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover28.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover28ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        rSButtonHover29.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover29.setText("5");
        rSButtonHover29.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover29.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover29.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover29.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover29ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        rSButtonHover30.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover30.setText("4");
        rSButtonHover30.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover30.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover30.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover30.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover30ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        rSButtonHover31.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover31.setText("7");
        rSButtonHover31.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover31.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover31.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover31.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover31ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        rSButtonHover32.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover32.setText("%");
        rSButtonHover32.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover32.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover32.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover32.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover32ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        rSButtonHover33.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover33.setText("Clr");
        rSButtonHover33.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover33.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover33.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover33.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover33ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        rSButtonHover34.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover34.setText("X");
        rSButtonHover34.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover34.setColorTextHover(new java.awt.Color(255, 51, 0));
        rSButtonHover34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover34.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover34.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover34.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover34ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover34, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        rSButtonHover35.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonHover35.setText("9");
        rSButtonHover35.setColorText(new java.awt.Color(51, 0, 51));
        rSButtonHover35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonHover35.setMaximumSize(new java.awt.Dimension(61, 45));
        rSButtonHover35.setMinimumSize(new java.awt.Dimension(61, 45));
        rSButtonHover35.setPreferredSize(new java.awt.Dimension(61, 45));
        rSButtonHover35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover35ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover35, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover10ActionPerformed
        // TODO add your handling code here:
        double t=Math.sin(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover10ActionPerformed

    private void rSButtonHover6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover6ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(jTextField1.getText());
        
        t= t*t;
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
        
    }//GEN-LAST:event_rSButtonHover6ActionPerformed

    private void rSButtonHover24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover24ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"0");
    }//GEN-LAST:event_rSButtonHover24ActionPerformed

    private void rSButtonHover25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover25ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"1");
    }//GEN-LAST:event_rSButtonHover25ActionPerformed

    private void rSButtonHover26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover26ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_rSButtonHover26ActionPerformed

    private void rSButtonHover27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover27ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_rSButtonHover27ActionPerformed

    private void rSButtonHover30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover30ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_rSButtonHover30ActionPerformed

    private void rSButtonHover29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover29ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_rSButtonHover29ActionPerformed

    private void rSButtonHover28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover28ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_rSButtonHover28ActionPerformed

    private void rSButtonHover31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover31ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_rSButtonHover31ActionPerformed

    private void rSButtonHover9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover9ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"8");
    }//GEN-LAST:event_rSButtonHover9ActionPerformed

    private void rSButtonHover35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover35ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+"9");
    }//GEN-LAST:event_rSButtonHover35ActionPerformed

    private void rSButtonHover23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover23ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText()+".");
    }//GEN-LAST:event_rSButtonHover23ActionPerformed

    private void rSButtonHover33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover33ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_rSButtonHover33ActionPerformed

    private void rSButtonHover34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover34ActionPerformed
        // TODO add your handling code here:
        String backSpace = null;
        if(jTextField1.getText().length()>0)
        {
            StringBuilder str = new StringBuilder(jTextField1.getText());
            str.deleteCharAt(jTextField1.getText().length()-1);
            backSpace = str.toString();
            jTextField1.setText(backSpace);
        }
    }//GEN-LAST:event_rSButtonHover34ActionPerformed

    private void rSButtonHover17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover17ActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr = "+";
    }//GEN-LAST:event_rSButtonHover17ActionPerformed

    private void rSButtonHover18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover18ActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr = "-";
    }//GEN-LAST:event_rSButtonHover18ActionPerformed

    private void rSButtonHover19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover19ActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr = "*";
    }//GEN-LAST:event_rSButtonHover19ActionPerformed

    private void rSButtonHover20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover20ActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr = "/";
    }//GEN-LAST:event_rSButtonHover20ActionPerformed

    private void rSButtonHover32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover32ActionPerformed
        // TODO add your handling code here:
         num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr = "%";
    }//GEN-LAST:event_rSButtonHover32ActionPerformed

    private void rSButtonHover22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover22ActionPerformed
        // TODO add your handling code here:
        num2 = Double.parseDouble(jTextField1.getText());
        
        if(opr == "+"){
            result = num1+num2;
            jTextField1.setText(Double.toString(result));
        }else if(opr == "-"){
            result = num1-num2;
            jTextField1.setText(Double.toString(result));
            
        }else if(opr == "*"){
            result = num1*num2;
            jTextField1.setText(Double.toString(result));
            
        }else if(opr == "/"){
            result = num1/num2;
            jTextField1.setText(Double.toString(result));
            
        }else if(opr == "%"){
            result = num1%num2;
            jTextField1.setText(Double.toString(result));
            
        }else if(opr == "x^y"){
            for(int i=0;i<num2;i++){
                result= num1*num2;
            }
            jTextField1.setText(Double.toString(result));
            
        }
    }//GEN-LAST:event_rSButtonHover22ActionPerformed

    private void rSButtonHover11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover11ActionPerformed
        // TODO add your handling code here:
        double t=Math.cos(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover11ActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
        // TODO add your handling code here:
        double t=Math.tan(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void rSButtonHover14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover14ActionPerformed
        // TODO add your handling code here:
        double t=Math.sinh(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover14ActionPerformed

    private void rSButtonHover15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover15ActionPerformed
        // TODO add your handling code here:
        double t=Math.cosh(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover15ActionPerformed

    private void rSButtonHover16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover16ActionPerformed
        // TODO add your handling code here:
        double t=Math.tanh(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover16ActionPerformed

    private void rSButtonHover13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover13ActionPerformed
        // TODO add your handling code here:
        double t=Math.log(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover13ActionPerformed

    private void rSButtonHover12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover12ActionPerformed
        // TODO add your handling code here:
        double t=Math.exp(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover12ActionPerformed

    private void rSButtonHover8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover8ActionPerformed
        // TODO add your handling code here:
        double t=Math.sqrt(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover8ActionPerformed

    private void rSButtonHover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover3ActionPerformed
        // TODO add your handling code here:
        double t=1/(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover3ActionPerformed

    private void rSButtonHover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover5ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(jTextField1.getText());
        
        t= t*t*t;
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_rSButtonHover5ActionPerformed

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr = "x^y";
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover7ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(jTextField1.getText());
        double f=1;
        while(t!=0){
            f=f*t;
            t--;
        }
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+f);
    }//GEN-LAST:event_rSButtonHover7ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        enable();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        disable();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
        double t=Double.parseDouble(String.valueOf(jTextField1.getText()));
        
        t=t*(-1);
        jTextField1.setText(String.valueOf(t));
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private rojeru_san.complementos.RSButtonHover rSButtonHover10;
    private rojeru_san.complementos.RSButtonHover rSButtonHover11;
    private rojeru_san.complementos.RSButtonHover rSButtonHover12;
    private rojeru_san.complementos.RSButtonHover rSButtonHover13;
    private rojeru_san.complementos.RSButtonHover rSButtonHover14;
    private rojeru_san.complementos.RSButtonHover rSButtonHover15;
    private rojeru_san.complementos.RSButtonHover rSButtonHover16;
    private rojeru_san.complementos.RSButtonHover rSButtonHover17;
    private rojeru_san.complementos.RSButtonHover rSButtonHover18;
    private rojeru_san.complementos.RSButtonHover rSButtonHover19;
    private rojeru_san.complementos.RSButtonHover rSButtonHover2;
    private rojeru_san.complementos.RSButtonHover rSButtonHover20;
    private rojeru_san.complementos.RSButtonHover rSButtonHover22;
    private rojeru_san.complementos.RSButtonHover rSButtonHover23;
    private rojeru_san.complementos.RSButtonHover rSButtonHover24;
    private rojeru_san.complementos.RSButtonHover rSButtonHover25;
    private rojeru_san.complementos.RSButtonHover rSButtonHover26;
    private rojeru_san.complementos.RSButtonHover rSButtonHover27;
    private rojeru_san.complementos.RSButtonHover rSButtonHover28;
    private rojeru_san.complementos.RSButtonHover rSButtonHover29;
    private rojeru_san.complementos.RSButtonHover rSButtonHover3;
    private rojeru_san.complementos.RSButtonHover rSButtonHover30;
    private rojeru_san.complementos.RSButtonHover rSButtonHover31;
    private rojeru_san.complementos.RSButtonHover rSButtonHover32;
    private rojeru_san.complementos.RSButtonHover rSButtonHover33;
    private rojeru_san.complementos.RSButtonHover rSButtonHover34;
    private rojeru_san.complementos.RSButtonHover rSButtonHover35;
    private rojeru_san.complementos.RSButtonHover rSButtonHover4;
    private rojeru_san.complementos.RSButtonHover rSButtonHover5;
    private rojeru_san.complementos.RSButtonHover rSButtonHover6;
    private rojeru_san.complementos.RSButtonHover rSButtonHover7;
    private rojeru_san.complementos.RSButtonHover rSButtonHover8;
    private rojeru_san.complementos.RSButtonHover rSButtonHover9;
    // End of variables declaration//GEN-END:variables
}
